# Generated by Django 5.2.17 on 2026-09-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coldfront_pve_provisioner", "0005_retirement_backup_retention"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionerConfiguration",
            fields=[
                (
                    "singleton",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "resource_name",
                    models.CharField(default="Proxmox Virtual Machine", max_length=100),
                ),
                (
                    "resource_description",
                    models.TextField(
                        default="Self-service virtual machines provisioned on Proxmox VE."
                    ),
                ),
                ("allocation_limit", models.PositiveSmallIntegerField(default=1)),
                ("service_term_months", models.PositiveSmallIntegerField(default=6)),
                (
                    "operating_system",
                    models.CharField(default="Linux cloud image", max_length=100),
                ),
                (
                    "guest_username",
                    models.CharField(default="cloud-user", max_length=32),
                ),
                ("vmid_min", models.PositiveIntegerField(default=1100)),
                ("vmid_max", models.PositiveIntegerField(default=1199)),
                (
                    "ipv4_pool_start",
                    models.GenericIPAddressField(
                        default="192.0.2.100", protocol="IPv4"
                    ),
                ),
                (
                    "ipv4_pool_end",
                    models.GenericIPAddressField(
                        default="192.0.2.199", protocol="IPv4"
                    ),
                ),
                ("network_prefix_length", models.PositiveSmallIntegerField(default=24)),
                (
                    "gateway",
                    models.GenericIPAddressField(default="192.0.2.1", protocol="IPv4"),
                ),
                (
                    "nameservers",
                    models.TextField(
                        default="1.1.1.1\n1.0.0.1",
                        help_text="One IPv4 address per line.",
                    ),
                ),
                (
                    "dns_search_domain",
                    models.CharField(default="example.org", max_length=253),
                ),
                (
                    "hostname_template",
                    models.CharField(
                        default="coldfront-a{allocation_id}-v{vmid}.{domain}",
                        help_text="Available fields: {allocation_id}, {vmid}, and {domain}.",
                        max_length=253,
                    ),
                ),
                ("template_vmid", models.PositiveIntegerField(default=9000)),
                (
                    "template_name",
                    models.CharField(
                        default="coldfront-linux-cloud-template", max_length=128
                    ),
                ),
                ("storage", models.CharField(default="local-lvm", max_length=64)),
                ("bridge", models.CharField(default="vmbr0", max_length=64)),
                ("cpu_type", models.CharField(default="x86-64-v2-AES", max_length=64)),
                (
                    "allowed_nodes",
                    models.TextField(help_text="One PVE node name per line."),
                ),
                (
                    "proxmox_pool",
                    models.CharField(default="coldfront-managed", max_length=64),
                ),
                (
                    "cloud_init_vendor_snippet",
                    models.CharField(
                        blank=True,
                        help_text="Optional PVE storage snippet reference, such as local:snippets/site.yml.",
                        max_length=255,
                    ),
                ),
                (
                    "netbox_cluster_type",
                    models.CharField(default="Proxmox VE", max_length=64),
                ),
                (
                    "netbox_cluster_name",
                    models.CharField(default="coldfront-pve", max_length=100),
                ),
                (
                    "netbox_managed_tag",
                    models.SlugField(default="coldfront-managed", max_length=100),
                ),
                ("guest_access_enabled", models.BooleanField(default=False)),
                (
                    "guest_access_group",
                    models.CharField(default="coldfront-vm-access", max_length=64),
                ),
                (
                    "guest_user_group",
                    models.CharField(default="coldfront-vm-users", max_length=64),
                ),
                (
                    "guest_access_helper",
                    models.CharField(
                        default="/usr/local/libexec/coldfront-vm-access-reconcile",
                        max_length=255,
                    ),
                ),
                ("retirement_enabled", models.BooleanField(default=False)),
                (
                    "retirement_backup_storage",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "retirement_backup_retention_days",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PVE provisioner configuration",
                "verbose_name_plural": "PVE provisioner configuration",
            },
        ),
        migrations.CreateModel(
            name="ProvisionerFlavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("cores", models.PositiveSmallIntegerField()),
                ("memory_mib", models.PositiveIntegerField()),
                ("disk_gib", models.PositiveIntegerField()),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "code"),
            },
        ),
    ]
