# Generated by Django 5.2.17 on 2026-09-19 04:56

from django.db import migrations, models


def preserve_existing_netbox_integrations(apps, schema_editor):
    configuration = apps.get_model(
        "coldfront_pve_provisioner", "ProvisionerConfiguration"
    )
    # Before this migration every configured installation required NetBox.
    # Preserve that behavior for existing rows while new configurations use
    # the field default and start with the optional mirror disabled.
    configuration.objects.update(netbox_enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        (
            "coldfront_pve_provisioner",
            "0006_provisionerconfiguration_provisionerflavor",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAddressReservation",
            fields=[],
            options={
                "verbose_name": "IP address reservation",
                "verbose_name_plural": "IP address reservations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("coldfront_pve_provisioner.virtualmachine",),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="netbox_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Mirror VM, interface, and IP records to NetBox. The built-in pool remains authoritative.",
                verbose_name="NetBox inventory mirroring",
            ),
        ),
        migrations.RunPython(
            preserve_existing_netbox_integrations, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="dns_search_domain",
            field=models.CharField(
                default="example.org",
                help_text="DNS search domain and default suffix available to the hostname template.",
                max_length=253,
                verbose_name="DNS search domain",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="gateway",
            field=models.GenericIPAddressField(
                default="192.0.2.1",
                help_text="Default IPv4 gateway; it must not be inside the allocation pool.",
                protocol="IPv4",
                verbose_name="IPv4 gateway",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="ipv4_pool_end",
            field=models.GenericIPAddressField(
                default="192.0.2.199",
                help_text="Last usable IPv4 address in the built-in allocation pool.",
                protocol="IPv4",
                verbose_name="IPv4 pool end",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="ipv4_pool_start",
            field=models.GenericIPAddressField(
                default="192.0.2.100",
                help_text="First usable IPv4 address in the built-in allocation pool.",
                protocol="IPv4",
                verbose_name="IPv4 pool start",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="network_prefix_length",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="IPv4 CIDR prefix length applied to provisioned VMs.",
                verbose_name="IPv4 prefix length",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="nameservers",
            field=models.TextField(
                default="1.1.1.1\n1.0.0.1",
                help_text="One IPv4 address per line.",
                verbose_name="DNS nameservers",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="netbox_cluster_name",
            field=models.CharField(
                default="coldfront-pve",
                max_length=100,
                verbose_name="NetBox cluster name",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="netbox_cluster_type",
            field=models.CharField(
                default="Proxmox VE",
                max_length=64,
                verbose_name="NetBox cluster type",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="netbox_managed_tag",
            field=models.SlugField(
                default="coldfront-managed",
                max_length=100,
                verbose_name="NetBox managed tag",
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="vmid_max",
            field=models.PositiveIntegerField(
                default=1199, verbose_name="VMID maximum"
            ),
        ),
        migrations.AlterField(
            model_name="provisionerconfiguration",
            name="vmid_min",
            field=models.PositiveIntegerField(
                default=1100, verbose_name="VMID minimum"
            ),
        ),
    ]
