# Generated by Django 5.2.17 on 2026-09-19 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coldfront_pve_provisioner", "0007_ipaddressreservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_enable_services",
            field=models.BooleanField(
                default=True,
                help_text="Enable and start configured units after package or file reconciliation.",
                verbose_name="Enable configured services",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_package_manager",
            field=models.CharField(
                choices=[
                    ("none", "Do not manage packages"),
                    ("dnf", "DNF (RHEL, Rocky, Alma, Fedora)"),
                    ("apt", "APT (Debian, Ubuntu)"),
                ],
                default="none",
                max_length=8,
                verbose_name="Package manager",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_packages",
            field=models.TextField(
                blank=True,
                help_text="One package name per line. Shell commands and arguments are not accepted.",
                verbose_name="Packages",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_patch_interval_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Zero disables scheduled patch jobs. Manual patch jobs use the same policy.",
                verbose_name="Patch interval (days)",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_patch_mode",
            field=models.CharField(
                choices=[
                    ("none", "Do not patch"),
                    ("security", "Security updates only"),
                    ("all", "All available updates"),
                ],
                default="none",
                max_length=8,
                verbose_name="Patch policy",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_policy_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Apply configured packages, files, and services through the versioned guest helper contract.",
                verbose_name="Declarative guest policy",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_policy_helper",
            field=models.CharField(
                default="/usr/local/libexec/coldfront-guest-reconcile",
                help_text="Absolute path to the reviewed in-guest helper installed by the image or cloud-init.",
                max_length=255,
                verbose_name="Guest policy helper",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_reconcile_on_membership_change",
            field=models.BooleanField(
                default=True,
                help_text="Queue guest policy after active allocation users are added or removed. Existing directory-access reconciliation remains independently configurable.",
                verbose_name="Reconcile when allocation membership changes",
            ),
        ),
        migrations.AddField(
            model_name="provisionerconfiguration",
            name="guest_service_units",
            field=models.TextField(
                blank=True,
                help_text="One .service, .socket, or .timer unit per line.",
                verbose_name="Systemd units",
            ),
        ),
        migrations.AddField(
            model_name="provisioningjob",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="virtualmachine",
            name="guest_patched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualmachine",
            name="guest_policy_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualmachine",
            name="guest_policy_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="virtualmachine",
            name="guest_policy_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="provisioningjob",
            name="action",
            field=models.CharField(
                choices=[
                    ("Provision", "Provision"),
                    ("Reconcile", "Reconcile guest"),
                    ("Patch", "Patch guest"),
                    ("Retire", "Retire"),
                ],
                default="Provision",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="GuestManagedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Absolute destination beneath /etc, /opt, or /usr/local.",
                        max_length=255,
                    ),
                ),
                (
                    "content_template",
                    models.TextField(
                        help_text="Non-secret UTF-8 content. Supported variables: allocation_id, vmid, hostname, ipv4_address, allocation_users_lines, allocation_users_json, and allocation_users_ldap_filter."
                    ),
                ),
                ("owner", models.CharField(default="root", max_length=32)),
                ("group", models.CharField(default="root", max_length=32)),
                ("mode", models.CharField(default="0644", max_length=4)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_managed_files",
                        to="coldfront_pve_provisioner.provisionerconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "guest managed file",
                "verbose_name_plural": "guest managed files",
                "ordering": ("sort_order", "path"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("configuration", "path"),
                        name="pve_one_guest_managed_path",
                    )
                ],
            },
        ),
    ]
